apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: appointme
  annotations:
    gatus.home-operations.com/enabled: "true"
    gatus.home-operations.com/endpoint: |
      group: appointment
      extra-labels:
        app_type: backend
      interval: 1m
      conditions:
        - "[CONNECTED] == true"
        - "[RESPONSE_TIME] < 500"
  labels:
    app: mcp-server
spec:
  selector:
    app: mcp-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
